-- ============================================================================
-- Migration 022: AI Website Chatbot
--
-- Adds:
--   - chatbot_config: per-brand public widget customization (greeting message,
--     accent color, avatar style). One row per brand.
--   - chatbot_sessions: one row per visitor chat session on the embedded widget
--     (client-generated session id, conversation history, scored temperature,
--     and the lead it produced once contact details are captured).
--
-- Idempotent: safe to re-run (IF NOT EXISTS / guarded). lead_temperature enum
-- is defined in schema.sql.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- chatbot_config: brand-scoped widget appearance (one per brand)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chatbot_config (
    config_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    brand_id         UUID NOT NULL REFERENCES brands (brand_id) ON DELETE CASCADE,
    greeting_message TEXT,
    accent_color     VARCHAR(20) NOT NULL DEFAULT '#f59e0b',
    avatar_style     VARCHAR(20) NOT NULL DEFAULT 'initials',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (brand_id)
);

CREATE INDEX IF NOT EXISTS idx_chatbot_config_brand_id ON chatbot_config (brand_id);

-- ----------------------------------------------------------------------------
-- chatbot_sessions: one visitor conversation on the embedded widget
--   session_id is generated by the widget (public, unauthenticated visitors),
--   so it is a client-supplied TEXT primary key.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chatbot_sessions (
    session_id           TEXT PRIMARY KEY,
    brand_id             UUID NOT NULL REFERENCES brands (brand_id) ON DELETE CASCADE,
    lead_id              UUID REFERENCES leads (lead_id) ON DELETE SET NULL,
    conversation_history JSONB NOT NULL DEFAULT '[]'::jsonb,
    temperature          lead_temperature,
    started_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_active_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chatbot_sessions_brand_id ON chatbot_sessions (brand_id);
CREATE INDEX IF NOT EXISTS idx_chatbot_sessions_lead_id ON chatbot_sessions (lead_id);
CREATE INDEX IF NOT EXISTS idx_chatbot_sessions_last_active
    ON chatbot_sessions (brand_id, last_active_at DESC);

-- updated_at trigger for config (set_updated_at() defined in schema.sql)
DROP TRIGGER IF EXISTS trg_chatbot_config_updated_at ON chatbot_config;
CREATE TRIGGER trg_chatbot_config_updated_at BEFORE UPDATE ON chatbot_config
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
