-- Google Ads starter plans generated by the Setup Agent when a user opts in to
-- running Google Search ads during onboarding. One initial plan per brand
-- (brand_id UNIQUE) so a retry after a crash can't create duplicates and an
-- ON CONFLICT backstops concurrent double-runs. Keywords are the real AI
-- keyword-research output (never mocked).
CREATE TABLE IF NOT EXISTS google_ad_plans (
  plan_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_id       UUID NOT NULL UNIQUE REFERENCES brands (brand_id) ON DELETE CASCADE,
  location       TEXT,
  monthly_budget NUMERIC(10, 2),
  keywords       JSONB NOT NULL DEFAULT '[]'::jsonb,
  status         TEXT NOT NULL DEFAULT 'draft',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
