// Prompt 018 (D-27) — task-spine adoption for Facebook ad launches.
//
// Proves the binding requirements:
//  1. Every launch runs through the canonical ad_launch task:
//     APPROVED → QUEUED → EXECUTING → PROVIDER_ACCEPTED (only with ALL FOUR
//     Facebook ids) → EXTERNALLY_VERIFIED (Prompt 005 read-back, proof row
//     REFERENCED never copied) → REPORTED → COMPLETED.
//  2. Source identity: the campaigns.campaign_id is pre-generated by the
//     adopter; success AND launch_failed rows share the task's source id.
//  3. Partial chain (D-27 §11) → EXTERNAL_FAILURE with partial ids in
//     evidence; a "success" without all four ids can never reach
//     PROVIDER_ACCEPTED.
//  4. State agreement (§3): campaigns.status vs task state — a disagreement
//     THROWS under NODE_ENV=test, never silently reconciled.
//  5. §13 regression: FB chain succeeds + spine recording fails → exactly one
//     launch (no relaunch), one campaigns row, and the reconciliation scan
//     rebuilds the trail with ZERO provider calls.
//  6. Reconciliation detections: campaigns rows with FB ids and no task;
//     stale EXECUTING ad_launch tasks → MANUAL_REVIEW; proof rows whose task
//     lost the proof reference get re-linked.
//  7. Verification-failure after a successful launch → MANUAL_REVIEW, never a
//     retry. Persist-failure → PROVIDER_ACCEPTED + MANUAL_REVIEW.
//  8. Prompt 015 wiring: pause/unpause audits attach evidence events to the
//     SAME terminal launch task (no new task, no state change).
//  9. Tenant isolation on the activity endpoints is inherited from taskSpine
//     (covered there); here we prove the trail lands under the right brand.

const { test, before, after, beforeEach } = require("node:test");
const assert = require("node:assert/strict");
const { db, createTestUser, deleteUser } = require("./helpers");
const { encrypt } = require("../utils/encryption");
const taskSpine = require("../utils/taskSpine");
const adLaunchSpine = require("../utils/adLaunchSpine");
const campaignController = require("../controllers/campaignController");

const { launchFacebookCampaign } = campaignController;

let userId;
let brandId;
let brand;

// ---- Graph API fetch mock (same recipe as facebookAdObject.test.js) --------
const realFetch = global.fetch;
let graphCalls; // [{ method, path, params }]
let failOnPath = null; // POST path suffix that should fail
let failReadBack = false; // make verification GETs fail
let idPrefix = "ls"; // per-test unique Facebook ids when needed

function installFetchMock() {
  graphCalls = [];
  global.fetch = async (url, opts = {}) => {
    const u = new URL(String(url));
    if (!u.hostname.endsWith("graph.facebook.com")) {
      throw new Error(`Unexpected non-Graph fetch in test: ${u.hostname}`);
    }
    const pathName = u.pathname.replace(/^\/v[\d.]+/, "");
    const params = {};
    for (const [k, v] of u.searchParams.entries()) params[k] = v;
    const method = opts.method || "GET";
    graphCalls.push({ method, path: pathName, params });

    if (method === "POST" && failOnPath && pathName.endsWith(failOnPath)) {
      return {
        ok: false,
        status: 400,
        headers: { get: () => null },
        text: async () =>
          JSON.stringify({ error: { message: "Simulated Graph failure", code: 100 } }),
      };
    }

    if (method === "GET") {
      if (failReadBack) {
        return {
          ok: false,
          status: 500,
          headers: { get: () => null },
          text: async () =>
            JSON.stringify({ error: { message: "Simulated read-back outage", code: 2 } }),
        };
      }
      // Prompt 005 read-back: campaign / adset object reads + the /ads list.
      if (pathName.endsWith("/ads")) {
        return {
          ok: true,
          status: 200,
          headers: { get: () => null },
          text: async () =>
            JSON.stringify({ data: [{ id: `ad_${idPrefix}`, status: "PAUSED", effective_status: "PAUSED" }] }),
        };
      }
      return {
        ok: true,
        status: 200,
        headers: { get: () => null },
        text: async () =>
          JSON.stringify({ id: pathName.slice(1), status: "PAUSED", effective_status: "PAUSED" }),
      };
    }

    let id = "unknown";
    if (pathName.endsWith("/campaigns")) id = `cmp_${idPrefix}`;
    else if (pathName.endsWith("/adsets")) id = `as_${idPrefix}`;
    else if (pathName.endsWith("/adcreatives")) id = `cr_${idPrefix}`;
    else if (pathName.endsWith("/ads")) id = `ad_${idPrefix}`;
    return {
      ok: true,
      status: 200,
      headers: { get: () => null },
      text: async () => JSON.stringify({ id }),
    };
  };
}

async function connectFacebook(uid) {
  await db.query(
    `INSERT INTO api_integrations
       (user_id, platform, api_token_encrypted, account_ref, facebook_pages, connection_status)
     VALUES ($1, 'facebook', $2, $3, $4::jsonb, 'connected')
     ON CONFLICT (user_id, platform) DO UPDATE
       SET api_token_encrypted = EXCLUDED.api_token_encrypted,
           account_ref = EXCLUDED.account_ref,
           facebook_pages = EXCLUDED.facebook_pages,
           connection_status = 'connected'`,
    [
      uid,
      encrypt(`token-for-${uid}`),
      "act_777001",
      JSON.stringify([{ id: "1500123456789", name: "Launch Spine Page" }]),
    ]
  );
}

function taskOf(campaignId) {
  return taskSpine.findTaskBySource({
    taskType: "ad_launch",
    sourceType: "campaign",
    sourceId: String(campaignId),
  });
}

async function eventsOf(taskId) {
  const { rows } = await db.query(
    "SELECT * FROM agent_task_events WHERE task_id = $1 ORDER BY created_at ASC, event_id ASC",
    [taskId]
  );
  return rows;
}

function statusPath(events) {
  return events.map((e) => e.to_status);
}

before(async () => {
  userId = await createTestUser();
  const b = await db.query(
    `INSERT INTO brands (user_id, brand_name, facebook_page_id, ad_link_url)
     VALUES ($1, 'Launch Spine Brand', '1500123456789', 'https://example.test/landing')
     RETURNING *`,
    [userId]
  );
  brand = b.rows[0];
  brandId = brand.brand_id;
  await connectFacebook(userId);
});

after(async () => {
  global.fetch = realFetch;
  const { rows } = await db.query("SELECT task_id FROM agent_tasks WHERE brand_id = $1", [brandId]);
  await db.query("ALTER TABLE agent_task_events DISABLE TRIGGER trg_agent_task_events_immutable");
  for (const r of rows) {
    await db.query("DELETE FROM agent_task_events WHERE task_id = $1", [r.task_id]);
  }
  await db.query("ALTER TABLE agent_task_events ENABLE TRIGGER trg_agent_task_events_immutable");
  await db.query("DELETE FROM agent_tasks WHERE brand_id = $1", [brandId]);
  // external_proofs rows are immutable (that's the point) — disable the
  // trigger for cleanup only, mirroring externalProofs.test.js.
  await db.query("ALTER TABLE external_proofs DISABLE TRIGGER trg_external_proofs_immutable");
  await db.query("DELETE FROM external_proofs WHERE brand_id = $1", [brandId]);
  await db.query("ALTER TABLE external_proofs ENABLE TRIGGER trg_external_proofs_immutable");
  await deleteUser(userId);
  await db.pool.end();
});

beforeEach(async () => {
  installFetchMock();
  failOnPath = null;
  failReadBack = false;
  idPrefix = "ls";
  await db.query("DELETE FROM campaigns WHERE user_id = $1", [userId]);
});

// --- 1. Full flow ------------------------------------------------------------

test("happy path: full trail APPROVED→…→COMPLETED, proof referenced, shared source id", async () => {
  const launched = await launchFacebookCampaign({
    userId,
    brand,
    goal: "leads",
    budget: 10,
    creativeOverride: { headline: "H", primaryText: "P" },
  });

  const task = await taskOf(launched.campaignId);
  assert.ok(task, "canonical ad_launch task exists keyed by the campaigns.campaign_id");
  assert.equal(task.status, "COMPLETED");
  assert.equal(task.task_type, "ad_launch");
  assert.equal(task.brand_id, brandId);
  assert.equal(task.external_ref, "cmp_ls", "external_ref is the Facebook campaign id");

  const events = await eventsOf(task.task_id);
  assert.deepEqual(statusPath(events), [
    "APPROVED",
    "QUEUED",
    "EXECUTING",
    "PROVIDER_ACCEPTED",
    "EXTERNALLY_VERIFIED",
    "REPORTED",
    "COMPLETED",
  ]);

  // Origin recorded on the creation event.
  assert.equal(events[0].meta.origin, "manual");
  // All four ids in the PROVIDER_ACCEPTED evidence.
  const accepted = events.find((e) => e.to_status === "PROVIDER_ACCEPTED");
  assert.deepEqual(accepted.meta.facebook, {
    campaignId: "cmp_ls",
    adSetId: "as_ls",
    creativeId: "cr_ls",
    adId: "ad_ls",
  });

  // Evidence is REFERENCED, never copied: proof_id points at external_proofs.
  assert.ok(task.proof_id, "task stores the proof reference");
  const proof = await db.query("SELECT * FROM external_proofs WHERE proof_id = $1", [task.proof_id]);
  assert.equal(proof.rows.length, 1);
  assert.equal(proof.rows[0].action, "launch_readback");
  assert.equal(proof.rows[0].external_id, "cmp_ls");
  assert.equal(proof.rows[0].run_key, `task-${task.task_id}`);
  assert.ok(proof.rows[0].evidence.readBack, "verbatim read-back stored in the proof, not the task");

  // Campaigns row shares the pre-generated id and agrees with the task state.
  const row = await db.query("SELECT * FROM campaigns WHERE campaign_id = $1", [launched.campaignId]);
  assert.equal(row.rows[0].status, "created_paused");
  assert.ok(adLaunchSpine.statesAgree("created_paused", task.status));
});

test("origin propagates: autopilot-labelled launches carry origin=autopilot", async () => {
  const launched = await launchFacebookCampaign({
    userId,
    brand,
    goal: "leads",
    budget: 5,
    creativeOverride: { headline: "H", primaryText: "P" },
    spineActor: `owner:${userId}`,
    spineOrigin: "autopilot",
  });
  const task = await taskOf(launched.campaignId);
  const events = await eventsOf(task.task_id);
  assert.equal(events[0].meta.origin, "autopilot");
  assert.equal(events[0].actor, `owner:${userId}`, "approval actor is the owner");
  const executing = events.find((e) => e.to_status === "EXECUTING");
  assert.equal(executing.actor, "system:ad-launch", "system actor from EXECUTING onward");
});

// --- 2. Failures ---------------------------------------------------------------

test("partial chain: EXTERNAL_FAILURE with partial ids; launch_failed row shares the source id", async () => {
  failOnPath = "/ads";
  await assert.rejects(
    launchFacebookCampaign({
      userId,
      brand,
      goal: "leads",
      budget: 10,
      creativeOverride: { headline: "H", primaryText: "P" },
    })
  );

  const row = await db.query(
    "SELECT * FROM campaigns WHERE user_id = $1 AND status = 'launch_failed'",
    [userId]
  );
  assert.equal(row.rows.length, 1, "exactly one launch_failed row");
  const task = await taskOf(row.rows[0].campaign_id);
  assert.ok(task, "failure row and task share the pre-generated campaign_id");
  assert.equal(task.status, "EXTERNAL_FAILURE");
  const events = await eventsOf(task.task_id);
  const failure = events.find((e) => e.to_status === "EXTERNAL_FAILURE");
  assert.equal(failure.meta.partialChain.campaignId, "cmp_ls");
  assert.equal(failure.meta.partialChain.creativeId, "cr_ls");
  assert.equal(failure.meta.partialChain.adId, null, "the failed object is honestly null");
  assert.ok(adLaunchSpine.statesAgree("launch_failed", "EXTERNAL_FAILURE"));
});

test("pre-chain failure (no destination) classifies VALIDATION_FAILED, zero Graph calls", async () => {
  const bare = { ...brand, facebook_page_id: null, ad_link_url: null };
  await assert.rejects(
    launchFacebookCampaign({
      userId,
      brand: bare,
      goal: "leads",
      budget: 10,
      creativeOverride: { headline: "H", primaryText: "P" },
    })
  );
  assert.equal(graphCalls.filter((c) => c.method === "POST").length, 0, "no Facebook object created");
  const { rows } = await db.query(
    `SELECT * FROM agent_tasks
      WHERE brand_id = $1 AND task_type = 'ad_launch'
      ORDER BY created_at DESC LIMIT 1`,
    [brandId]
  );
  assert.equal(rows[0].status, "VALIDATION_FAILED");
});

test("verification read-back failure after a successful launch → MANUAL_REVIEW, no retry", async () => {
  failReadBack = true;
  const launched = await launchFacebookCampaign({
    userId,
    brand,
    goal: "leads",
    budget: 10,
    creativeOverride: { headline: "H", primaryText: "P" },
  });
  const posts = graphCalls.filter((c) => c.method === "POST");
  assert.equal(posts.length, 4, "the chain ran exactly once — no relaunch on verify failure");
  const task = await taskOf(launched.campaignId);
  assert.equal(task.status, "MANUAL_REVIEW");
  const events = await eventsOf(task.task_id);
  const parked = events.find((e) => e.to_status === "MANUAL_REVIEW");
  assert.equal(parked.meta.reason, "verification_failed");
  assert.ok(!events.some((e) => e.to_status === "EXTERNALLY_VERIFIED"), "never a false verification");
  // campaigns row stays created_paused (verify failure never changes domain state).
  const row = await db.query("SELECT status FROM campaigns WHERE campaign_id = $1", [launched.campaignId]);
  assert.equal(row.rows[0].status, "created_paused");
  assert.ok(adLaunchSpine.statesAgree("created_paused", "MANUAL_REVIEW"));
});

test("persist failure: PROVIDER_ACCEPTED (ids attached) then MANUAL_REVIEW, never relaunch", async () => {
  const rec = await adLaunchSpine.beginLaunch({
    brandId,
    userId,
    actor: `owner:${userId}`,
    origin: "manual",
    title: "persist-failure test",
  });
  const ids = { campaignId: "cmp_p", adSetId: "as_p", creativeId: "cr_p", adId: "ad_p" };
  await adLaunchSpine.recordPersistFailure({
    taskId: rec.taskId,
    campaignId: rec.campaignId,
    brandId,
    userId,
    ids,
    error: new Error("insert failed"),
  });
  const events = await eventsOf(rec.taskId);
  assert.deepEqual(statusPath(events).slice(-2), ["PROVIDER_ACCEPTED", "MANUAL_REVIEW"]);
  const review = events[events.length - 1];
  assert.equal(review.meta.reason, "persist_failed");
  assert.deepEqual(review.meta.facebook, ids);
});

test("completeness gate: a 'success' without all four ids can never reach PROVIDER_ACCEPTED", async () => {
  const rec = await adLaunchSpine.beginLaunch({
    brandId,
    userId,
    actor: `owner:${userId}`,
    title: "incomplete-chain test",
  });
  await adLaunchSpine.recordLaunchSuccess({
    taskId: rec.taskId,
    campaignId: rec.campaignId,
    brandId,
    userId,
    ids: { campaignId: "cmp_x", adSetId: "as_x", creativeId: null, adId: "ad_x" },
  });
  const events = await eventsOf(rec.taskId);
  assert.ok(!events.some((e) => e.to_status === "PROVIDER_ACCEPTED"));
  assert.equal(events[events.length - 1].to_status, "EXTERNAL_FAILURE");
  assert.equal(events[events.length - 1].meta.reason, "incomplete_chain");
});

// --- 3. Classification + state agreement ------------------------------------

test("classifyLaunchFailure: partial chain always EXTERNAL_FAILURE; pre-chain by cause", () => {
  const c = adLaunchSpine.classifyLaunchFailure;
  const none = { campaignId: null, adSetId: null, creativeId: null, adId: null };
  assert.equal(c(new Error("anything"), { ...none, campaignId: "cmp" }), "EXTERNAL_FAILURE");
  assert.equal(c(Object.assign(new Error("x"), { statusCode: 401 }), none), "AUTH_REQUIRED");
  assert.equal(c(new Error("Facebook token expired — reconnect"), none), "AUTH_REQUIRED");
  assert.equal(c(Object.assign(new Error("x"), { statusCode: 403 }), none), "PERMISSION_DENIED");
  assert.equal(c(new Error("rate limit reached"), none), "RATE_LIMITED");
  assert.equal(c(new Error("No Facebook Page destination configured"), none), "VALIDATION_FAILED");
  assert.equal(c(new Error("weird unexplained thing"), none), "EXTERNAL_FAILURE");
});

test("statesAgree covers the mapping; disagreement THROWS in tests", async () => {
  assert.ok(adLaunchSpine.statesAgree("created_paused", "COMPLETED"));
  assert.ok(adLaunchSpine.statesAgree("live", "COMPLETED"));
  assert.ok(adLaunchSpine.statesAgree("launch_failed", "MANUAL_REVIEW"));
  assert.ok(!adLaunchSpine.statesAgree("launch_failed", "COMPLETED"));
  assert.ok(!adLaunchSpine.statesAgree("created_paused", "EXTERNAL_FAILURE"));
  await assert.rejects(
    adLaunchSpine.enforceStateAgreement({
      campaignId: "00000000-0000-0000-0000-000000000000",
      brandId,
      userId,
      campaignStatus: "launch_failed",
      taskStatus: "COMPLETED",
    }),
    /state disagreement/
  );
});

// --- 4. §13 regression: spine down, launch unaffected, scan rebuilds ---------

test("§13: spine recording fails → ONE launch, one row, scan rebuilds with zero provider calls", async () => {
  // Unique Facebook ids so no earlier test's proof row (same mock ids) can
  // satisfy the rebuilt trail's proof lookup.
  idPrefix = "s13";
  const realCreate = taskSpine.createTask;
  const realTransition = taskSpine.transition;
  taskSpine.createTask = async () => {
    throw new Error("simulated spine outage");
  };
  taskSpine.transition = async () => {
    throw new Error("simulated spine outage");
  };
  let launched;
  try {
    launched = await launchFacebookCampaign({
      userId,
      brand,
      goal: "leads",
      budget: 10,
      creativeOverride: { headline: "H", primaryText: "P" },
    });
  } finally {
    taskSpine.createTask = realCreate;
    taskSpine.transition = realTransition;
  }
  // Launch unaffected: exactly four POSTs, one campaigns row.
  assert.equal(graphCalls.filter((c) => c.method === "POST").length, 4);
  const rows = await db.query("SELECT * FROM campaigns WHERE user_id = $1", [userId]);
  assert.equal(rows.rows.length, 1);
  assert.equal(rows.rows[0].status, "created_paused");
  assert.equal(await taskOf(launched.campaignId), null, "no task was recorded during the outage");

  // Reconciliation scan rebuilds the trail — with ZERO provider calls.
  const callsBefore = graphCalls.length;
  const result = await taskSpine.scanForMissingTasks({ lookbackHours: 1, limit: 10 });
  assert.equal(graphCalls.length, callsBefore, "scan made no Facebook call");
  assert.ok(result.launchesRepaired >= 1);
  const task = await taskOf(launched.campaignId);
  assert.ok(task, "trail rebuilt");
  // Honesty rule: no proof exists, so it reports verification unavailable —
  // it never fabricates EXTERNALLY_VERIFIED.
  const events = await eventsOf(task.task_id);
  assert.ok(!events.some((e) => e.to_status === "EXTERNALLY_VERIFIED"));
  const reported = events.find((e) => e.to_status === "REPORTED");
  assert.equal(reported.meta.verification, "unavailable");
  assert.equal(task.status, "COMPLETED");
});

// --- 5. Reconciliation detections ---------------------------------------------

test("scan rebuilds a launch_failed row with no task as EXTERNAL_FAILURE", async () => {
  const ins = await db.query(
    `INSERT INTO campaigns
       (brand_id, user_id, campaign_name, budget, ad_creative_variations,
        launch_date, facebook_campaign_id, status, last_verify_error)
     VALUES ($1, $2, 'orphan failed', 5, '[]', CURRENT_DATE, 'cmp_orphan', 'launch_failed', 'chain broke')
     RETURNING campaign_id`,
    [brandId, userId]
  );
  await taskSpine.repairOneCampaign(ins.rows[0].campaign_id);
  const task = await taskOf(ins.rows[0].campaign_id);
  assert.equal(task.status, "EXTERNAL_FAILURE");
  assert.equal(task.last_error, "chain broke");
  const events = await eventsOf(task.task_id);
  assert.equal(events[0].meta.reconstructed, true);
});

test("scan reuses an existing launch_readback proof by reference when rebuilding", async () => {
  // Unique per run: external_proofs is append-only across runs, and run_key +
  // action carry a unique constraint.
  const fbId = `cmp_proofed_${Date.now()}`;
  const ins = await db.query(
    `INSERT INTO campaigns
       (brand_id, user_id, campaign_name, budget, ad_creative_variations, launch_date,
        facebook_campaign_id, facebook_adset_id, facebook_creative_id, facebook_ad_id, status)
     VALUES ($1, $2, 'orphan ok', 5, '[]', CURRENT_DATE, $3, 'as_2', 'cr_2', 'ad_2', 'created_paused')
     RETURNING campaign_id`,
    [brandId, userId, fbId]
  );
  const proof = await db.query(
    `INSERT INTO external_proofs (run_key, provider, action, external_id, brand_id, user_id, environment, evidence)
     VALUES ($3, 'facebook', 'launch_readback', $4, $1, $2, 'test', '{}')
     RETURNING proof_id`,
    [brandId, userId, `preexisting-${Date.now()}`, fbId]
  );
  await taskSpine.repairOneCampaign(ins.rows[0].campaign_id);
  const task = await taskOf(ins.rows[0].campaign_id);
  assert.equal(task.status, "COMPLETED");
  assert.equal(String(task.proof_id), String(proof.rows[0].proof_id), "existing proof referenced, not copied");
  const events = await eventsOf(task.task_id);
  assert.ok(events.some((e) => e.to_status === "EXTERNALLY_VERIFIED"));
});

test("scan parks stale EXECUTING ad_launch tasks in MANUAL_REVIEW", async () => {
  const rec = await adLaunchSpine.beginLaunch({
    brandId,
    userId,
    actor: `owner:${userId}`,
    title: "stale launch",
  });
  await db.query("UPDATE agent_tasks SET updated_at = NOW() - INTERVAL '2 hours' WHERE task_id = $1", [
    rec.taskId,
  ]);
  await taskSpine.scanForMissingTasks({ lookbackHours: 1, limit: 10 });
  const { rows } = await db.query("SELECT status, last_error FROM agent_tasks WHERE task_id = $1", [
    rec.taskId,
  ]);
  assert.equal(rows[0].status, "MANUAL_REVIEW");
  assert.match(rows[0].last_error, /interrupted/i);
});

test("scan re-links a launch_readback proof whose task lost the reference", async () => {
  const rec = await adLaunchSpine.beginLaunch({
    brandId,
    userId,
    actor: `owner:${userId}`,
    title: "proof relink",
  });
  const ids = { campaignId: "cmp_r", adSetId: "as_r", creativeId: "cr_r", adId: "ad_r" };
  await taskSpine.transition({ taskId: rec.taskId, to: "PROVIDER_ACCEPTED", actor: "system:ad-launch" });
  const proof = await db.query(
    `INSERT INTO external_proofs (run_key, provider, action, external_id, brand_id, user_id, environment, evidence)
     VALUES ($1, 'facebook', 'launch_readback', 'cmp_r', $2, $3, 'test', $4)
     RETURNING proof_id`,
    [`task-${rec.taskId}`, brandId, userId, JSON.stringify({ facebook: ids })]
  );
  const res = await taskSpine.scanForMissingTasks({ lookbackHours: 1, limit: 10 });
  assert.ok(res.proofsRelinked >= 1);
  const { rows } = await db.query("SELECT proof_id FROM agent_tasks WHERE task_id = $1", [rec.taskId]);
  assert.equal(String(rows[0].proof_id), String(proof.rows[0].proof_id));
});

// --- 6. Prompt 015 wiring ------------------------------------------------------

test("pause/unpause evidence attaches to the SAME terminal launch task — no new task, no state change", async () => {
  const launched = await launchFacebookCampaign({
    userId,
    brand,
    goal: "leads",
    budget: 10,
    creativeOverride: { headline: "H", primaryText: "P" },
  });
  const task = await taskOf(launched.campaignId);
  assert.equal(task.status, "COMPLETED");

  await adLaunchSpine.attachLifecycleEvidence({
    campaignId: launched.campaignId,
    actor: `owner:${userId}`,
    meta: { event: "unpause", result: "success", auditId: "audit-123" },
  });

  const afterTask = await taskOf(launched.campaignId);
  assert.equal(afterTask.status, "COMPLETED", "state unchanged — wiring only");
  const { rows: taskCount } = await db.query(
    `SELECT COUNT(*)::int AS n FROM agent_tasks
      WHERE task_type = 'ad_launch' AND source_id = $1`,
    [String(launched.campaignId)]
  );
  assert.equal(taskCount[0].n, 1, "no new task per unpause");
  const events = await eventsOf(task.task_id);
  const evidence = events[events.length - 1];
  assert.equal(evidence.meta.event, "unpause");
  assert.equal(evidence.meta.auditId, "audit-123");
  assert.equal(evidence.from_status, "COMPLETED");
  assert.equal(evidence.to_status, "COMPLETED");
});
