// Echo Self-Review — admin API (platform-level, admin-only via adminRoutes).
//
// Sage's weekly study of the platform itself: reports are generated by the
// Monday cron (utils/selfReview.js) or on demand here. Recommendation-only —
// these endpoints never change any system; item status is just the admin's
// own triage (new / planned / dismissed / done).

const db = require("../config/db");
const selfReview = require("../utils/selfReview");

const ITEM_STATUSES = ["new", "planned", "dismissed", "done"];

/** GET /api/admin/self-review/reports — newest first, with item counts. */
async function listReports(req, res) {
  try {
    const { rows } = await db.query(
      `SELECT r.report_id, r.week_start, r.status, r.summary, r.error,
              r.created_at, r.completed_at,
              COUNT(i.item_id)::int AS item_count,
              COUNT(i.item_id) FILTER (WHERE i.status = 'new')::int AS new_count
         FROM self_review_reports r
         LEFT JOIN self_review_items i ON i.report_id = r.report_id
        GROUP BY r.report_id
        ORDER BY r.week_start DESC
        LIMIT 26`,
    );
    res.json({ reports: rows });
  } catch (err) {
    console.error("Self-review list error:", err.message);
    res.status(500).json({ error: "Failed to load self-review reports" });
  }
}

/** GET /api/admin/self-review/reports/:reportId — full report + ranked items. */
async function getReport(req, res) {
  try {
    const { reportId } = req.params;
    const reportRes = await db.query(
      `SELECT report_id, week_start, status, summary, evidence, error,
              created_at, completed_at
         FROM self_review_reports
        WHERE report_id = $1`,
      [reportId],
    );
    if (reportRes.rows.length === 0) {
      return res.status(404).json({ error: "Report not found" });
    }
    const itemsRes = await db.query(
      `SELECT item_id, rank, title, recommendation, evidence, impact, status
         FROM self_review_items
        WHERE report_id = $1
        ORDER BY rank ASC`,
      [reportId],
    );
    res.json({ report: reportRes.rows[0], items: itemsRes.rows });
  } catch (err) {
    console.error("Self-review get error:", err.message);
    res.status(500).json({ error: "Failed to load the report" });
  }
}

/**
 * POST /api/admin/self-review/run — generate this week's report now.
 * Completed week → 409 (one study per week; the data doesn't change midweek).
 * Failed week → atomically reset and regenerated. AI failure → 502 (honest).
 */
async function runNow(req, res) {
  try {
    const result = await selfReview.runWeeklySelfReview({ rerunFailed: true });
    if (result.status === "already_completed") {
      return res.status(409).json({
        error: "This week's self-review is already complete.",
        reportId: result.reportId,
      });
    }
    if (result.status === "already_running") {
      return res.status(409).json({
        error: "A self-review is already running for this week.",
        reportId: result.reportId,
      });
    }
    if (result.status === "failed") {
      return res.status(502).json({
        error: result.error || "The AI study failed. The gathered data was kept — try again.",
        reportId: result.reportId,
      });
    }
    res.json({ message: "Self-review complete.", reportId: result.reportId });
  } catch (err) {
    console.error("Self-review run error:", err.message);
    res.status(500).json({ error: "Failed to run the self-review" });
  }
}

/** PUT /api/admin/self-review/items/:itemId/status — admin triage of an item. */
async function updateItemStatus(req, res) {
  try {
    const { itemId } = req.params;
    const status = req.body && req.body.status;
    if (!ITEM_STATUSES.includes(status)) {
      return res
        .status(400)
        .json({ error: `status must be one of: ${ITEM_STATUSES.join(", ")}` });
    }
    const { rows } = await db.query(
      `UPDATE self_review_items
          SET status = $2, updated_at = NOW()
        WHERE item_id = $1
        RETURNING item_id, status`,
      [itemId, status],
    );
    if (rows.length === 0) return res.status(404).json({ error: "Item not found" });
    res.json({ item: rows[0] });
  } catch (err) {
    console.error("Self-review item update error:", err.message);
    res.status(500).json({ error: "Failed to update the item" });
  }
}

module.exports = { listReports, getReport, runNow, updateItemStatus };
